POST http://localhost:5000/users HTTP/1.1
content-type: application/json

  {
    "id": "ef8ac118-8d7f-49cc-abec-78e0d05af80a",
    "user_name": "mstefa",
    "password": "Test1234",
    "first_name": "matias",
    "last_name": "stefanutti",
    "email": "mstefanutti24@gmail.com",
    "country_id": "US",
    "roles": ["USER"],
    "phone_number": "+543415552618"
  }
